-- MySQL Workbench Synchronization
-- Generated: 2023-03-29 15:50
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: corio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `escola`.`aluno` (
  `MATRICULA` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NULL DEFAULT NULL,
  `SEXO` CHAR(1) NULL DEFAULT NULL,
  `IDADE` INT(2) NULL DEFAULT NULL,
  `RUA` VARCHAR(45) NULL DEFAULT NULL,
  `NUMERO` INT(11) NULL DEFAULT NULL,
  `COMPLEMENTO` VARCHAR(45) NULL DEFAULT NULL,
  `turma_COD` INT(11) NOT NULL,
  PRIMARY KEY (`MATRICULA`, `turma_COD`),
  INDEX `fk_aluno_turma_idx` (`turma_COD` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_turma`
    FOREIGN KEY (`turma_COD`)
    REFERENCES `escola`.`turma` (`COD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `escola`.`turma` (
  `COD` INT(11) NOT NULL,
  `SALA` VARCHAR(45) NULL DEFAULT NULL,
  `DESCRICAO_SALA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`COD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
