# Generated by Django 5.0.2 on 2024-02-21 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_remove_deposito_setor_estoque_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
